### Site Settings ###
title               : Sunchit Lakhanpal
description         : >-
                      Flutter Aficionado, Mobile Application Developer :iphone: , Interested in Deep Learning & AI :thought_balloon:
baseurl             : ""
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Sunchit Lakhanpal
  image             : assets/pic.jpg
  email             : lakhanpalsunchit8@gmail.com
  github            : sunchit17
  instagram         : sunchit_17
  linkedin          : sunchit17
  soundcloud        : sunchit-lakhanpal
  twitter           : SLakhanpal17

### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
disqus: sunchitl                          # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
